language: ruby
rvm:
- 2.2.2
sudo: false
before_script:
  - pip install --user yamllint
  - pip install --user yamale
  - gem install html-proofer
script:
  - yamllint _pages/*
  - ruby tests/test_filesRootDirectory.rb
  - ruby tests/test_fileEndingsPins.rb
  - ruby tests/test_HTML.rb
  - bundle exec jekyll build
